version: 0.0
os: linux


files:

  - source: /
    destination: /home/xen/basic-crud-express

hooks:

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  
